name: Remote pull ssh
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run remote pull
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                    whoami
                    ls -al
                    mkdir repo
                    cd repo
                    ls -al